#ifndef TACO_TASK_IDS_H
#define TACO_TASK_IDS_H

enum TACOTaskID {
  TID_TOP_LEVEL = 1000,
  TID_TACO_FILL_TASK,
  TID_TACO_VALIDATE_TASK,
  TID_INIT_CUBLAS,
  TID_ATTACH_COO_REGIONS,
  TID_ATTACH_SPECIFIC_REGION,
  TID_DUMMY_READ_REGION,
  TID_SPARSE_GATHER_PARTITION,
  TID_RECT_COMPRESSED_FINALIZE_YIELD_POSITIONS,
  TID_RECT_COMPRESSED_GET_SEQ_INSERT_EDGES_LOCAL_SCAN,
  TID_RECT_COMPRESSED_GET_SEQ_INSERT_EDGES_APPLY_PARTIAL_RESULTS,
  TID_RECT_COMPRESSED_POS_PARTITION_DOWNWARDS,
  TID_RECT_COMPRESSED_COORDINATE_PARTITION,
  TID_INIT_CUSPARSE,
  TID_COPY_RECT_TO_NORMAL_POS,
};

#endif //TACO_TASK_IDS_H
