#ifndef TACO_TASK_IDS_H
#define TACO_TASK_IDS_H

enum TACOTaskID {
  TID_TOP_LEVEL = 1000,
  TID_TACO_FILL_TASK,
  TID_TACO_VALIDATE_TASK,
  TID_INIT_CUBLAS,
  TID_ATTACH_COO_REGIONS,
  TID_ATTACH_DIM_REGION,
};

#endif //TACO_TASK_IDS_H
